[package]
name = "common"
version = "0.1.9"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bincode = "1.3.3"
widestring = "1.0.2"
windows-sys = { version = "0.48.0", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_LibraryLoader",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_Threading",
  "Win32_System_Memory",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_SystemInformation"
] }
serde = { version = "1.0.188", features = ["derive"] }
lazy_static = "1.4.0"
directories = "5.0.1"
serde_json = "1.0.107"
injectors = "0.1.2"
retour = { version = "0.3.1", features = ["static-detour"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
