[package]
name = "version"
version = "0.1.9"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.56"
chrono = "0.4.19"
common = { path = "../common" }
directories = "4.0.1"
injectors = "0.1.2"
vc-ltl = "5.0.5"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[build-dependencies]
forward-dll = "0.1.12"
